config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'

  get "/team" => "pages#team"
  get "/contact" => "pages#join_us"

  resources :products
  resources :upvotes, only: [ :create, :destroy ]

  # #Read action routes
  # get "/products" => "products#index"
  # get "/products/:id" => "products#show"
  #
  # #Create action routes
  # get "/products/new" => "products#new"
  # post "/products" => "products#create"
  #
  # #Update action routes
  # get "/products/:id/edit" => "products#edit"
  # patch "/products/:id" => "products#update"
  #
  # #Delete action route
  # delete "/products/:id" => "products#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_attachment :photo
  has_many :upvotes
  belongs_to :user

  validates :user, presence: true
  validates :name, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true
  validates :category, inclusion: {in: %w(tech education design), message: "%{value} is not a valid category"}
end

app/models/upvote.rb
class Upvote < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :user, uniqueness: { scope: :product }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
  has_many :upvotes
  has_attachment :avatar

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def voted_for?(product)
    product.upvotes.where(user: self).any?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,        keys: [:avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
    @today = Date.today
    @products = Product.all
  end
  def team
    @members = ["Nico", "Romain", "Julie"]
  end
  def join_us
    render plain: "Send us a mail !"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :find_product, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category]
      @products = Product.select { |product| product.category == params[:category] }
      # @products = Product.where(category: params[:category])
    else
      @products = Product.all
    end
  end

  def show
    # @product = Product.find(params[:id]) i.e find_product
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    # @product = Product.find(params[:id]) i.e find_product
  end

  def update
    # @product = Product.find(params[:id]) i.e find_product
    if @product.user == current_user
      if @product.update(product_params)
        redirect_to products_path
      else
        render :edit
      end
    end
  end

  def destroy
    # @product = Product.find(params[:id]) i.e find_product
    if @product.user == current_user
      @product.destroy
    end
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :url, :tagline, :category, :photo)
  end

  def find_product
    @product = Product.find(params[:id])
  end

end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  def create
    @product = Product.find(params[:product_id])
    @product.upvotes.create! user: current_user

    respond_to do |format|
      format.html { redirect_to products_path }
      format.js
    end
  end

  def destroy
    upvote = Upvote.find(params[:id])
    @product = upvote.product
    upvote.destroy
    respond_to do |format|
      format.html { redirect_to products_path }
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>TODO</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
</head>
<body>
  <%= render "/shared/navbar" %>
  <%= render "/shared/flashes" %>
  <%= yield %>
  <%= javascript_include_tag 'application' %>
  <%= cloudinary_js_config %>
</body>
</html>

app/views/pages/home.html.erb
<div class="banner"
     style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%),
     url('<%= image_path "background.jpg" %>');">
  <div class="banner-content">
    <h1>WAGON HUNT</h1>
    <p>The best new products, every day</p>
    <p>
      <%= @products.count %> new products on <%= @today %>
    </p>
    <p>
      <%= link_to "View All Products", products_path, class: "btn btn-success btn-lg" %>
    </p>
  </div>
</div>

<div class="container padded">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <%= link_to "Design", products_path(category: "design"), class: "card-category design" %>
    </div>
    <div class="col-xs-12 col-sm-4">
      <%= link_to "Tech", products_path(category: "tech"), class: "card-category tech" %>
    </div>
    <div class="col-xs-12 col-sm-4">
      <%= link_to "Education", products_path(category: "education"), class: "card-category education" %>
    </div>
  </div>
</div>

app/views/pages/team.html.erb
<div class="container text-center">
  <h1>Meet the team</h1>

  <%= cl_image_tag "gbkeg45agdda1q0ppkmp", height: 300 %>

  <ul>
    <% @members.each do |member| %>
      <li><%= member %></li>
    <% end %>
  </ul>
</div>

app/views/products/_form.html.erb
<%= simple_form_for @product do |f| %>
  <%= f.input :name, placeholder: "Google", label: "Product Name" %>
  <%= f.input :url, placeholder: "https://google.com", label: "URL" %>
  <%= f.input :tagline, placeholder: "Don't be evil", label: "Tagline" %>
  <%= f.input :category, collection: ["tech", "education", "design"], prompt: "Choose a category" %>
  <%= f.input :photo, as: :attachinary %>
  <%= f.button :submit, "Submit", class: "btn btn-primary" %>
  <%= link_to "Back", products_path, class: "btn btn-success" %>
<% end %>



<!-- <form action="/products" method="post">

  <div class="form-group">
    <label for="name">Nom de produit:</label>
    <input type="text" name="product[name]" class="form-control" placeholder="Google" id="name">
  </div>

  <div class="form-group">
    <label for="url">URL du produit:</label>
    <input type="text" name="product[url]" class="form-control" placeholder="https://google.com" id="url">
  </div>

  <input type="submit" value="Soumettre" class="btn btn-primary">

</form> -->

app/views/products/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1 class="title text-center">Edit the product</h1>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1 class="title text-center">ALL PRODUCTS</h1>
      <ul>
        <% @products.each do |product| %>
          <div class="product">

            <div class="upvote_container" id="product-<%= product.id %>">
              <%= render "upvotes/show_upvote", product: product %>
            </div>

            <% if product.photo? %>
              <%= cl_image_tag(product.photo.path, :height => 117, :crop => :fill, class: "product-image") %>
            <% else %>
              <img src="<%= image_path "background.jpg" %>" alt="startup image" class="product-image hidden-xs">
            <% end %>

            <div class='product-body'>
              <h3><%= link_to product.name, product_path(product) %></h3>
              <p><%= product.tagline %></p>
            </div>
            <ul class="list-inline product-controls hidden-sm hidden-xs">
              <li>
                <%= link_to product_path(product) do %>
                  <i class="fa fa-eye"></i>
                <% end %>
              </li>
              <li>
                <%= link_to edit_product_path(product) do %>
                  <i class="fa fa-pencil"></i>
                <% end %>
              </li>
              <li>
                <%= link_to product_path(product), method: :delete do %>
                  <i class="fa fa-trash"></i>
                <% end %>
              </li>
            </ul>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1 class="title text-center">Submit a product</h1>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="banner"
style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%),
url('<%= image_path "background.jpg" %>');">
  <div class="banner-content">
    <h1 class="title"><%= @product.name %></h1>
    <p>
      <%= @product.tagline %>
      <span class="label label-default"><%= @product.category %></span>
    </p>
    <% if @product.user %>
      <p>
        Posted by : <%= @product.user.email %>
      </p>
    <% end %>
    <% if @product.photo? %>
      <%= cl_image_tag @product.photo.path, width: 300 %>
    <% end %>
    <p><%= link_to "GET IT", @product.url, class: "btn btn-success btn-lg", target: :_blank %></p>
    <p class="light-font">
      <%= link_to "Edit", edit_product_path(@product), class: "btn btn-warning" %>
      <%= link_to "Delete", product_path(@product), method: :delete, class: "btn btn-danger"%>
    </p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "lewagon.png" %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>
      <!-- Text link -->
      <%= link_to "All Products", products_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.avatar? %>
            <%= cl_image_tag current_user.avatar.path, width: 40, height: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", :'data-toggle' => "dropdown" %>
          <% else %>
            <img src="http://placehold.it/50x50" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><a href="#">Profile</a></li>
            <li><a href="#">Dashboard</a></li>
            <li>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </div>
      </div>

      <!-- Button (call-to-action) -->
      <%= link_to "SUBMIT", new_product_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
    <% else %>
      <%= link_to "Log In", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Sign Up", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
    <% end %>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/upvotes/_show_upvote.html.erb
<% if user_signed_in? %>

  <% if current_user.voted_for?(product)%>

    <%= link_to upvote_path(current_user.upvotes.where(product: product).first), remote: true, class: 'product-upvote product-upvoted', method: :delete do %>
      <div class="product-arrow"></div>
      <div class='product-count'><%= product.upvotes.size %></div>
    <% end %>

  <% else %>

    <%= link_to upvotes_path(product_id: product.id), remote: true, class: 'product-upvote', method: :post do %>
      <div class="product-arrow"></div>
      <div class='product-count'><%= product.upvotes.size %></div>
    <% end %>

  <% end %>

<% else %>

  <div class="product-upvote">
    <div class="product-arrow"></div>
    <div class='product-count'><%= product.upvotes.size %></div>
  </div>

<% end %>

app/views/upvotes/create.js.erb
$('#product-<%= @product.id %>').html('<%= j render "upvotes/show_upvote", product: @product %>');

app/views/upvotes/destroy.js.erb
$('#product-<%= @product.id %>').html('<%= j render "upvotes/show_upvote", product: @product %>');